
<div class="flex-center position-ref full-height">
    <div class="content">
        <div class="title m-b-md">
            Hi, <?php print $_SESSION['account']['auth']; ?>
            <p class="secound-title">What you want to do today?</p>
        </div>

        <div class="links">
            <a href="<?php print WEB_URL; ?>/admin/create">Create Topic</a>
            <a href="<?php print WEB_URL; ?>/admin/manage">Manage Topics</a>
            <a href="<?php print WEB_URL; ?>/admin/users">Manage Users</a>
            <a href="<?php print WEB_URL; ?>/admin/qanda">Manage Q&A</a>
            <a href="<?php print WEB_URL; ?>/admin/web">Web Settings</a>
        </div>
    </div>
</div>