<div class="col-md-8">
	<table class="table-align table table-hover table-light" style="margin-top: 20px;">
		<thead>
			<tr>
				<th>ID</th>
				<th>Title</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			<?php if (!empty($this->view_data['posts'])) { foreach ($this->view_data['posts'] as $post): ?>
				<tr>
					<td><?php print $post['id']; ?></td>
					<td>
						<a target="_BLANK" href="<?php print WEB_URL.'/home/read/'.$post['id']; ?>">
							<?php print $post['title']; ?>
						</a>
					</td>
					<td>
						<a href="<?php print WEB_URL.'/admin/dtopic/'.$post['id']; ?>" title="Delete topic">
							<i class="fa fa-trash" style="color:red"></i>
						</a>
					</td>
				</tr>
			<?php endforeach; } ?>
		</tbody>
	</table>
</div>